#ifndef BOIDS_CONSTANTS_H
#define BOIDS_CONSTANTS_H

#define WINDOW_WIDTH 800
#define WINDOW_HEIGHT 600

#define NUM_BOIDS 10
#define VIEW_RADIUS 200
#define AVOIDANCE_RADIUS 40
#define ALIGNMENT_FACTOR 0.01
#define SEPARATION_FACTOR 0.05
#define COHESION_FACTOR 0.02
#define MAX_SPEED 5 // in px per frame
#define FIELD_OF_VIEW 360 // in degrees

#endif // BOIDS_CONSTANTS_H
