#ifndef BOIDS_CONSTANTS_H
#define BOIDS_CONSTANTS_H

#define WINDOW_WIDTH 1600
#define WINDOW_HEIGHT 800

#define NUM_BOIDS 100
#define VIEW_RADIUS 200
#define ARMLENGTH_RADIUS 40
#define ALIGNMENT_FACTOR 0.001
#define SEPARATION_FACTOR 0.05
#define COHERENCE_FACTOR 0.01

#define MAX_SPEED 5

#endif // BOIDS_CONSTANTS_H
